<?
$head="<!DOCTYPE html><html><head><title>File Share</title><link href='/css/bootstrap.min.css' rel='stylesheet'><link href='/css/bootstrap-responsive.min.css' rel='stylesheet'><meta name='viewport' content='width=device-width, initial-scale=1.0'></head><body>";

$greeting="<div class='alert alert-block'>
<a href='?_close_greeting=1' class='close' data-dismiss='alert'>&times;</a>
<h4>Добро пожаловать в файловое хранилище</h4> Для просмотра некоторых файлов в онлайн-режиме необходимо наличие аккаунта Google. Если аккаунта нет - файл можно просто скачать (для этого есть кнопка \"Скачать\").
</div>";

$counter='<!-- Yandex.Metrika informer --><a href="http://metrika.yandex.ru/stat/?id=7927513&amp;from=informer" target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/7927513/1_1_555555FF_353535FF_1_pageviews" style="width:80px; height:15px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры)" onclick="try{Ya.Metrika.informer({i:this,id:7927513,type:0,lang:\'ru\'});return false}catch(e){}"/></a><!-- /Yandex.Metrika informer --><!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter7927513 = new Ya.Metrika({id:7927513, clickmap:true, trackLinks:true, accurateTrackBounce:true, trackHash:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/7927513" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter --><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png" /></a><br><a href="https://bitbucket.org/darkrepulser/webdav-php-viewer/">Исходный код</a><br>';

$footerp="<footer><div class='container'><div class='span10 offset1'>&copy; Dark Repulser ". date('Y') . "<br>$counter</div></div></footer>";
$footern="<footer><div class='container'><div class='span6  offset3'>&copy; Dark Repulser ". date('Y') . "<br>$counter</div></div></footer>";
?>